// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApwbiJ0C3LzyWACZq97_8BncIxYC24noc',
    appId: '1:620188640445:web:ec778a893d28f79c5d03d4',
    messagingSenderId: '620188640445',
    projectId: 'perplexity-d4498',
    authDomain: 'perplexity-d4498.firebaseapp.com',
    storageBucket: 'perplexity-d4498.firebasestorage.app',
    measurementId: 'G-XFF0XECTLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0MXvYi8077DZVg2ktennaKxyZE_2XPQ',
    appId: '1:620188640445:android:c07b2a98cd6fc8305d03d4',
    messagingSenderId: '620188640445',
    projectId: 'perplexity-d4498',
    storageBucket: 'perplexity-d4498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wCA9EvJdX_3Zarfb9y54hCJGEWhh-_4',
    appId: '1:717061013926:ios:292e643fbf08477e210f67',
    messagingSenderId: '717061013926',
    projectId: 'perplexity-flutter-clone',
    storageBucket: 'perplexity-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wCA9EvJdX_3Zarfb9y54hCJGEWhh-_4',
    appId: '1:717061013926:ios:292e643fbf08477e210f67',
    messagingSenderId: '717061013926',
    projectId: 'perplexity-flutter-clone',
    storageBucket: 'perplexity-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXaLADNGwzBGEQj3rBnMTvvBVDjg1u7KQ',
    appId: '1:717061013926:web:92257f1d605a9ae7210f67',
    messagingSenderId: '717061013926',
    projectId: 'perplexity-flutter-clone',
    authDomain: 'perplexity-flutter-clone.firebaseapp.com',
    storageBucket: 'perplexity-flutter-clone.firebasestorage.app',
    measurementId: 'G-W08PSP7SCH',
  );

}